#!/usr/bin/env python3
"""Embed workflow and presentation helpers into the self-contained notebook."""
import argparse
import base64
import hashlib
import json
import re
from pathlib import Path


def expected_source(root):
    code = (root / "workflow_support.py").read_text(encoding="utf-8")
    sha = hashlib.sha256(code.encode()).hexdigest()
    presentation = (root / "workflow_presentation.py").read_text(encoding="utf-8")
    ui_sha = hashlib.sha256(presentation.encode()).hexdigest()
    return ("#@title 0) Load workflow helpers (run once)\n"
            "#@markdown Initialize the analysis and result-display helpers. Then continue to workspace settings below.\n"
            "# Generated by scripts/sync_notebook.py. Edit the source modules instead.\n"
            f"_WORKFLOW_SOURCE_SHA = {sha!r}\n" + code + "\n"
            f"_PRESENTATION_SOURCE_SHA = {ui_sha!r}\n" + presentation).splitlines(keepends=True)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    path = root / "workflow.ipynb"
    notebook = json.loads(path.read_text(encoding="utf-8"))
    cells = [cell for cell in notebook["cells"] if cell.get("id") == "workflow-support"]
    if len(cells) != 1:
        raise SystemExit("Expected one workflow-support cell.")
    replacements = [(cells[0], expected_source(root))]
    for identifier, asset in (("overview", "hero"), ("workflow-map", "workflow")):
        cell = next(c for c in notebook["cells"] if c.get("id") == identifier)
        data = base64.b64encode((root / "docs" / "assets" / f"{asset}.png").read_bytes()).decode()
        source, count = re.subn(r"data:image/png;base64,[^)]*", "data:image/png;base64," + data,
                               "".join(cell["source"]))
        if count != 1:
            raise SystemExit(f"Expected one embedded image in {identifier}.")
        replacements.append((cell, source.splitlines(keepends=True)))
    for cell, expected in replacements:
        if args.check and cell["source"] != expected:
            raise SystemExit(f"Cell {cell['id']} is stale. Run python scripts/sync_notebook.py.")
        cell["source"] = expected
    if not args.check:
        path.write_text(json.dumps(notebook, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
    else:
        print("Embedded analysis/display helpers and images match their source files.")


if __name__ == "__main__":
    main()
